### ISSUE TITLE
duvida

### ISSUE THREAD

**Issue by rnesheiksilvestre** [michelsouzafigueiredo/bombcryptobot#1]
me tira uma duvida, esse bot ele seleciona os heroes por raridade ? vi que no threashold tem declarado as raridade mas no codigo do bot não encontrei nada chamando alguma imagem ou algo do tipo

**Comment by michelsouzafigueiredo** [comment]
> me tira uma duvida, esse bot ele seleciona os heroes por raridade ? vi que no threashold tem declarado as raridade mas no codigo do bot não encontrei nada chamando alguma imagem ou algo do tipo

A principio não ta funcionando ainda, mas assim que der eu adiciono essa possibilidade ou pego de algum bot que adicionou e coloco aqui. Sempre que tiver algo bom novo eu vou ajustar aqui.

**Comment by rnesheiksilvestre** [comment]
> > me tira uma duvida, esse bot ele seleciona os heroes por raridade ? vi que no threashold tem declarado as raridade mas no codigo do bot não encontrei nada chamando alguma imagem ou algo do tipo
> 
> A principio não ta funcionando ainda, mas assim que der eu adiciono essa possibilidade ou pego de algum bot que adicionou e coloco aqui. Sempre que tiver algo bom novo eu vou ajustar aqui.

da uma olhada https://github.com/mpcabete/bombcrypto-bot/issues/527#issuecomment-1007093737 eu estava tentando colocar o envio por raridade exemplo.. seleciona os raro vai ao mapa deixa quebrando por 10 minutos volta e seleciona os comum.. por que fazer isso as vezes o bau está com a vida baixa e os raro acima solta mais bomba ai pode acontecer do raro solta duas bomba em 1 bau e somente com 1 bomba ele quebra o bau e a outra é desperdiçada... e olha esse pr https://github.com/mpcabete/bombcrypto-bot/pull/512 oque vc acha ?

**Comment by michelsouzafigueiredo** [comment]
> > > me tira uma duvida, esse bot ele seleciona os heroes por raridade ? vi que no threashold tem declarado as raridade mas no codigo do bot não encontrei nada chamando alguma imagem ou algo do tipo
> > 
> > 
> > A principio não ta funcionando ainda, mas assim que der eu adiciono essa possibilidade ou pego de algum bot que adicionou e coloco aqui. Sempre que tiver algo bom novo eu vou ajustar aqui.
> 
> da uma olhada [mpcabete/bombcrypto-bot#527 (comment)](https://github.com/mpcabete/bombcrypto-bot/issues/527#issuecomment-1007093737) eu estava tentando colocar o envio por raridade exemplo.. seleciona os raro vai ao mapa deixa quebrando por 10 minutos volta e seleciona os comum.. por que fazer isso as vezes o bau está com a vida baixa e os raro acima solta mais bomba ai pode acontecer do raro solta duas bomba em 1 bau e somente com 1 bomba ele quebra o bau e a outra é desperdiçada... e olha esse pr [mpcabete/bombcrypto-bot#512](https://github.com/mpcabete/bombcrypto-bot/pull/512) oque vc acha ?

vamos analisando, assim que surgir uma boa opção eu acoplo aqui

**Comment by Japa18244** [comment]
Como ficou a situação desse bot? @michelsouzafigueiredo ? Está funcionando a parte de mandar heróis específicos para baús específicos?

**Comment by michelsouzafigueiredo** [comment]
> Como ficou a situação desse bot? @michelsouzafigueiredo ? Está funcionando a parte de mandar heróis específicos para baús específicos?

Não, ainda não. Mas o bot está funcionando 100%.
